### ISSUE TITLE
External task are not marked as Transaction Boundaries

### ISSUE THREAD

**Issue by ingorichtsmeier** [camunda-community-hub/camunda-bpm-process-test-coverage#120]
If you test a process with an external service task and check the transaction boundaries in the coverage, the external task is not marked.

![grafik](https://user-images.githubusercontent.com/7870843/139301562-7bff24c5-a401-4178-a633-835b1590a2e8.png)

**Comment by zambrovski** [comment]
Hi @dominikhorn93,

since it seems to be an issue in the display component of the viewer, there is not much we can do inside this project, but need to get to the viewer component.... Is it somewhere on the web and is it open source? Might be a good idea :-)

Cheers,

Simon

**Comment by dominikhorn93** [comment]
Hi @zambrovski, @ingorichtsmeier,

I will ask my colleague @alex-parschek where it is.
Thought we have put that Open Source - but can’t find it.
It is a small React Component that does everything.

Best
Dominik

**Comment by alex-praschek** [comment]
Hi @zambrovski @ingorichtsmeier,

I just created a pull request (#125) to fix this issue. I also open-sourced the [flowcov-viewer](https://github.com/FlowSquad/flowcov-viewer) that is used in this library.

Best regards,
Alex
