### ISSUE TITLE
Path for reports is not configurable

### ISSUE THREAD

**Issue by arolfes** [camunda-community-hub/camunda-bpm-process-test-coverage#135]
We use gradle as our build tool and the default path in gradle for output is `<root_dir>/build`

all generated reports are saved under `<root_dir>/target/process-test-coverage`

So please make the output path for coverage reports configurable. The default can stick to `<root_dir>/target/process-test-coverage`

**Comment by arolfes** [comment]
Hi there,

Any news to on this issue?

**Comment by zambrovski** [comment]
Hi Alex,

sorry for no response. Thank you for the issue. Will implement it soon...
If you want to accelerate it, feel free to provide a PR for that.

**Comment by arolfes** [comment]
Hi @zambrovski ,

so far I figured out that it is configurable. 
class `org.camunda.bpm.extension.process_test_coverage.util.CoverageReportUtil`

`public static String TARGET_DIR_ROOT = System.getProperty("camunda-bpm-process-test-coverage.target-dir-root", "target/process-test-coverage/");`

it is just an undocument feature :-)
