### ISSUE TITLE
camunda-bpm-process-test-coverage-spring-test only available as Snapshot Version

### ISSUE THREAD

**Issue by borerra** [camunda-community-hub/camunda-bpm-process-test-coverage#144]
Hello,

We are using Camunda and wanted to add Test Coverage. We successfully managed to implement Testcoverage with the `camunda-bpm-process-test-coverage-junit4` Library. On top of that we also have some Spring Camunda test. We wanted to use `camunda-bpm-process-test-coverage-spring-test` mentioned on https://github.com/camunda-community-hub/camunda-bpm-process-test-coverage#readme.
Problem here is that this artifact only exists in the `camunda-bpm-community-extensions-snapshots` Repository but is missing in the `camunda-bpm-communty-extensions` Repository.
https://camunda.jfrog.io/ui/repos/tree/General/camunda-bpm-community-extensions-snapshots%2Forg%2Fcamunda%2Fbpm%2Fextension%2Fcamunda-bpm-process-test-coverage-spring-test%2F1.0.1-SNAPSHOT

Will you add a released version of this artifact to the repository?

Best Regard Raphael Borer

**Comment by zambrovski** [comment]
Will be released today.
