### ISSUE TITLE
I can't make this work

### ISSUE THREAD

**Issue by billbarni** [camunda-community-hub/camunda-bpm-process-test-coverage#163]
Running the JUnit5 coverage example, if you add anything to a Service Task and make it "Async Before", I can't "complete" that task anymore.

assertThat(processInstance).isWaitingAt("Activity_0lzx7k0"); // returns true
complete(task("Activity_0lzx7k0")); // task is null

How bad is this? I can't make this work properly and there is no running example anywhere of this being used correctly?
Searching the WHOLE Github returns me only results from this repo for "@ExtendWith(ProcessEngineCoverageExtension.class)"

No one is implementing this because it's absolute buggy?

**Comment by zambrovski** [comment]
Hello @billbarni,

I‘ll have a look on it.
I‘m using it a lot with bad without async with JUnit4. 

Cheers,

simon

**Comment by billbarni** [comment]
> Hello @billbarni,
> 
> I‘ll have a look on it. I‘m using it a lot with and without async with JUnit4.
> 
> Cheers,
> 
> simon

Forget about it!
