### ISSUE TITLE
Failed to read artifact descriptor for org.camunda.bpm.extension:camunda-bpm-process-test-coverage-starter:jar:1.0.2

### ISSUE THREAD

**Issue by mstislavm** [camunda-community-hub/camunda-bpm-process-test-coverage#166]
Hi team,

Spring Boot 2.5.4
Camunda 7.16

Unable to include dependency: camunda-bpm-process-test-coverage-starter.

`    <dependency>
      <groupId>org.camunda.bpm.extension</groupId>
      <artifactId>camunda-bpm-process-test-coverage-starter</artifactId>
      <version>${camunda-bpm-process-test-coverage.version}</version>
      <scope>test</scope>
    </dependency>`

`[INFO] Validation error:

[ERROR] org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.camunda.bpm.extension:camunda-bpm-process-test-coverage-starter:jar:1.0.2
[ERROR] Maven server structure problem`

**Comment by zambrovski** [comment]
Hi,

this is crazy, can you replay it and this time call `mvn clean package -U`.
Is the problem still there?

Cheers,

Simon

**Comment by mstislavm** [comment]
Hi,

It seems the problem is solved. I successfully import camunda-bpm-process-test-coverage-starter dependency.
Thanks!

WBR,

Mstislav

**Comment by zambrovski** [comment]
By the way, we released 1.0.3 and it is already available in the Maven central.
