### ISSUE TITLE
Link Intermediate Throw Events not part of junit5-coverage

### ISSUE THREAD

**Issue by schmuka0501** [camunda-community-hub/camunda-bpm-process-test-coverage#182]
I tried to update from version 0.4.0 to 1.0.3 and using junit5 instead of junit4. It works with 2 little flaws:

_Link Intermediate Throw Event_ are not counted as part of the coverage, therefore my test coverage is not 100% but something like 99.x%.

If you define the ProcessEngineCoverageExtension as a static variable annotated with @RegisterExtension inside the test, no coverage data is written (json file does not contain any data) and the html file is empty.

I created a sample project https://github.com/schmuka0501/bug-bpm-process-coverage, which shows both problems. I committed the result of my test https://github.com/schmuka0501/bug-bpm-process-coverage/tree/main/src/doc/process-test-coverage, too.

**Comment by rohwerj** [comment]
The problem with the report not being generated is, that the generation is triggered after the coverage assertion. I changed the order of the calls to always generate the report, even if the coverage assertion fails. 
The intermediate link throw event is a little tricky, as it's execution is not protocolled by the engine. My workaround is to not count these events as executable flow nodes (which they are really not in the engine).
The coverage will then be correct, but the graphical report will not color these nodes green. 
I'm not sure if this can be easily changed. 
Will do a little bit of cleaning up in the branch and then create a pull request.
