### ISSUE TITLE
Switch release building to GH Actions

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-bpm-process-test-coverage#72]
After the setup of the dev build and the comaptibility matrix build with GH actions (#66), the setup of the release to maven central should be switched to GH actions, like in most other extensions.

I'd like to get some support of @lwille here, since he proven his excellence in supporting most other extensions.

Leonhard, could you have a look and create a PR on this project please?

Cheers,

Simon

**Comment by lwille** [comment]
hi @zambrovski, thank you for the request! I've created an internal ticket INFRA-1910 to track this request and forwarded it to my team. As the 4th quarter is already tightly packed, I can already tell you that this will take some time, but we're going to try to accomodate it.

Kudos for your work regarding the compatibility test matrix, that looks really neat!

**Comment by zambrovski** [comment]
Thank you, I'll prepare some code by taking it over from another extension and let you review this. Are the git secrets provided on the Org-Level or per repository?

**Comment by zambrovski** [comment]
Hi @lwille,

I created the deploy workflow and committed it to the master branch. As you can see, (https://github.com/camunda/camunda-bpm-process-test-coverage/actions/runs/319994999) it is now failing to build because of missing secrets.. Would you be so kind and put them in for this repository...

Currently release is difficult and is performed via old Camunda jenkins and and seem to be problematic (see #63).

Cheers,

Simon

**Comment by chaima-mnsr** [comment]
Hi @zambrovski, 

Can you please try to rebuild the project, Leo and myself added the needed secrets and the pipeline should work fine. I tried to re-run it myself, but it seems possible only by pushing a commit. 

If it works as expected feel free to close the issue. Thanks
