### ISSUE TITLE
Implement event log serialization

### ISSUE THREAD

**Issue by zambrovski** [camunda-community-hub/camunda-bpm-process-test-coverage#76]
In order to allow for further processing, the coverage information needs to be stored in an intermediate representation in JSON.
Instead of storage of the coverage directly, an event log should be stored and used for further coverage calculations.

**Description**:

The event log consists of a list of `bpmnModel` elements. Each `bpmnModel` carries information about the process definition it is defined in (`processDefinitionKey`, `processDefinitionVersionTag`, `processDefinitionId`), the raw XML BPMN Model, the total element count (that is the sum of all flow and transition nodes from the model) and finally a collection of `suite`s.

Every `suite` consists of a name (which for example can be a full qualified class name of the test) and a list of `run`s, representing single executions. Every `run` has a name (which for example can be a method name of the test) and a list of `event`s. Every `event` represent a passed node in the process. 

Here is the first example:

```
{
  "version": "v1",
  "bpmnModels": [
    {
      "bpmnXml": "<XML...>"
      "processDefinitionKey": "StartWithFlowCov",
      "processDefinitionVersionTag": "v2",
      "processDefinitionVersionId": "2",
      "totalElementCount": 24,
      "hash": -377055457,
      "suites": [
        {
          "name": "io.flowcov.camunda.examples.simple.ProcessTest",
          "runs": [
            {
              "name": "deploy_process",
              "events": [
                {
                  "source": "FlowNode",
                  "type": "start|end|take",
                  "definitionKey": "StartEvent_TraceabilityWanted",
                  "elementType": "startEvent",
                  "timestamp": 1234543436657
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

```

**Comment by jangalinski** [comment]
NIce.

Questions:

a) what's the difference between versionTag and versionId?
b) what is the bpmnXml? the full xml? Don't think so ... so it would be best to use "ref" in the name ... an additional refType (filesystem, httpd, inmemory/generator,...) would also be useful, in case the tests are not running in the same module as the bpmn files
c) the events struct seems to be over simplified ... don't we need some kind of context? Otherwise, how can we determine loops, multi-instances or event-based sub-processes?

Did you discuss these?

Jan

**Comment by zambrovski** [comment]
Hey Jan,

yes we discussed the issues you are speaking about. Let me try to answer shortly:

a) versionTag is the tag you manually provide in modeler, versionId is the one generated by Camunda on deployment. For local development it should not matter, but for the initiative of FlowCov, you want to create reports over time and probably will group over processDefinitionKey. So it might be an interesting information for the user. In addition, if you are not collecting data from a JUnit test run, but rather from an integration test with a real system, the processVersionId shows the version of really deployed process in runtime.

b) `bpmnXml` is currently designed to contain the full XML of the process model. This is a first thing we want to support (and which is required for later rendering of the process coverage). We spoke about the fact, that in later version of this coverage information we might support references to external resources - files, urls or something else. For now, we start with the embedded process model as XML which gives us the ability to have a self-contained event log.

c) Could you be more specific on that statement? Do you have anything in mind we missed? The event has indeed several attributes describing the context: `source` can for now have values  `FlowNode` and `Transition? <not defined yet>`, the `type` is one of the `start`, `end` on flow node and `take` on transition, `definitionKey` is a pointer to the `id` attribute inside the BPMN model, `elementType` explains what flow node type we are on and will be one of all supported BPMN element types like `startEvent`, `callActivity`, `serviceTask`, `userTask`, `intermediateThrowingEvent`, ...

Cheers,

Simon

**Comment by jangalinski** [comment]
a: check
b: understood .. although embedding several kB of xml in a json file feels weird
c: what if the same element is executed several times from several contexts (aka executions)don't you want to store that execution-context for further analysis?

**Comment by zambrovski** [comment]
the log is serial, so for one run of the multi-instance, you will see the element occurring multiple times in the log.
