### ISSUE TITLE
Enhancement - Test coverage of groovy scripts

### ISSUE THREAD

**Issue by madmax25** [camunda-community-hub/camunda-bpm-process-test-coverage#89]
Would like to be able to drill into a node and see the groovy script and see the lines of script highlighted in green that are covered. Would like groovy script lines added to calculation of the coverage percentage.

**Comment by zambrovski** [comment]
Hi @madmax25,

thank you for the idea. I'm not sure this is intended by this extension. We speak about process coverage, not code coverage. 
I think coverage of script code (Groovy, Javascript or any other) is out of scope of this extension for the moment.

Cheers,

Simon

**Comment by madmax25** [comment]
Process coverage is a good start, but not a final answer. To achieve high coverage on the scripts, a gap will still need to be filled, perhaps by another open source project. @ingorichtsmeier
